// flow-typed signature: 1b2f4f9524323e56cc2c5cfc9f0f4832
// flow-typed version: <<STUB>>/alias-quokka-plugin_v^0.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'alias-quokka-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "alias-quokka-plugin" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "alias-quokka-plugin/src/main" {
  declare module.exports: any
}

// Filename aliases
declare module "alias-quokka-plugin/src/main.js" {
  declare module.exports: $Exports<"alias-quokka-plugin/src/main">
}
