// flow-typed signature: ac7cb9a75dccdf7af127bcf1ceea6037
// flow-typed version: <<STUB>>/babel-preset-flow-node_v^2.0.1/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-flow-node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "babel-preset-flow-node" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "babel-preset-flow-node/index" {
  declare module.exports: $Exports<"babel-preset-flow-node">
}
declare module "babel-preset-flow-node/index.js" {
  declare module.exports: $Exports<"babel-preset-flow-node">
}
