// flow-typed signature: 78b0a531d2285b5792920054a73a962c
// flow-typed version: <<STUB>>/babel-preset-flow-syntax_v1.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-preset-flow-syntax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "babel-preset-flow-syntax" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module "babel-preset-flow-syntax/index" {
  declare module.exports: $Exports<"babel-preset-flow-syntax">
}
declare module "babel-preset-flow-syntax/index.js" {
  declare module.exports: $Exports<"babel-preset-flow-syntax">
}
