// flow-typed signature: 6a6f3f6d122e2fd0f612f659f29fc981
// flow-typed version: <<STUB>>/blue-tape_v^1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blue-tape'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "blue-tape" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "blue-tape/bin/blue-tape" {
  declare module.exports: any
}

declare module "blue-tape/blue-tape" {
  declare module.exports: any
}

// Filename aliases
declare module "blue-tape/bin/blue-tape.js" {
  declare module.exports: $Exports<"blue-tape/bin/blue-tape">
}
declare module "blue-tape/blue-tape.js" {
  declare module.exports: $Exports<"blue-tape/blue-tape">
}
