// flow-typed signature: c40b7ddba5cb7a134e32365aee0f84b7
// flow-typed version: <<STUB>>/fast-diff_v1.1.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fast-diff'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "fast-diff" {
  declare export type INSERT = 1
  declare export type EQUAL = 0
  declare export type DELETE = -1

  declare export default {
    INSERT: INSERT,
    EQUAL: EQUAL,
    DELETE: DELETE,
    (string, string, ?number): Array<[INSERT | DELETE | EQUAL, string]>
  }
}
