// flow-typed signature: 51d88c16fdeccd2df425d88b30cd7492
// flow-typed version: <<STUB>>/markdown-it-checkbox_v1.1.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'markdown-it-checkbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "markdown-it-checkbox" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "markdown-it-checkbox/build/index" {
  declare module.exports: any
}

declare module "markdown-it-checkbox/dist/markdown-it-checkbox" {
  declare module.exports: any
}

declare module "markdown-it-checkbox/dist/markdown-it-checkbox.min" {
  declare module.exports: any
}

// Filename aliases
declare module "markdown-it-checkbox/build/index.js" {
  declare module.exports: $Exports<"markdown-it-checkbox/build/index">
}
declare module "markdown-it-checkbox/dist/markdown-it-checkbox.js" {
  declare module.exports: $Exports<
    "markdown-it-checkbox/dist/markdown-it-checkbox"
  >
}
declare module "markdown-it-checkbox/dist/markdown-it-checkbox.min.js" {
  declare module.exports: $Exports<
    "markdown-it-checkbox/dist/markdown-it-checkbox.min"
  >
}
declare module "markdown-it-checkbox/index" {
  declare module.exports: $Exports<"markdown-it-checkbox">
}
declare module "markdown-it-checkbox/index.js" {
  declare module.exports: $Exports<"markdown-it-checkbox">
}
