// flow-typed signature: aed761102b22b00f45b2d29c58d275f5
// flow-typed version: <<STUB>>/prosemirror-gapcursor_v1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-gapcursor'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prosemirror-gapcursor" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prosemirror-gapcursor/dist/index" {
  declare module.exports: any
}

declare module "prosemirror-gapcursor/rollup.config" {
  declare module.exports: any
}

declare module "prosemirror-gapcursor/src/gapcursor" {
  declare module.exports: any
}

declare module "prosemirror-gapcursor/src/index" {
  declare module.exports: any
}

// Filename aliases
declare module "prosemirror-gapcursor/dist/index.js" {
  declare module.exports: $Exports<"prosemirror-gapcursor/dist/index">
}
declare module "prosemirror-gapcursor/rollup.config.js" {
  declare module.exports: $Exports<"prosemirror-gapcursor/rollup.config">
}
declare module "prosemirror-gapcursor/src/gapcursor.js" {
  declare module.exports: $Exports<"prosemirror-gapcursor/src/gapcursor">
}
declare module "prosemirror-gapcursor/src/index.js" {
  declare module.exports: $Exports<"prosemirror-gapcursor/src/index">
}
