// flow-typed signature: 7b9617b73596ca7a6f882eb68fe1ee38
// flow-typed version: <<STUB>>/prosemirror-example-setup_v1.0.1/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-example-setup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prosemirror-example-setup" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prosemirror-example-setup/dist/index" {
  declare module.exports: any
}

declare module "prosemirror-example-setup/rollup.config" {
  declare module.exports: any
}

declare module "prosemirror-example-setup/src/index" {
  declare module.exports: any
}

declare module "prosemirror-example-setup/src/inputrules" {
  declare module.exports: any
}

declare module "prosemirror-example-setup/src/keymap" {
  declare module.exports: any
}

declare module "prosemirror-example-setup/src/menu" {
  declare module.exports: any
}

declare module "prosemirror-example-setup/src/prompt" {
  declare module.exports: any
}

// Filename aliases
declare module "prosemirror-example-setup/dist/index.js" {
  declare module.exports: $Exports<"prosemirror-example-setup/dist/index">
}
declare module "prosemirror-example-setup/rollup.config.js" {
  declare module.exports: $Exports<"prosemirror-example-setup/rollup.config">
}
declare module "prosemirror-example-setup/src/index.js" {
  declare module.exports: $Exports<"prosemirror-example-setup/src/index">
}
declare module "prosemirror-example-setup/src/inputrules.js" {
  declare module.exports: $Exports<"prosemirror-example-setup/src/inputrules">
}
declare module "prosemirror-example-setup/src/keymap.js" {
  declare module.exports: $Exports<"prosemirror-example-setup/src/keymap">
}
declare module "prosemirror-example-setup/src/menu.js" {
  declare module.exports: $Exports<"prosemirror-example-setup/src/menu">
}
declare module "prosemirror-example-setup/src/prompt.js" {
  declare module.exports: $Exports<"prosemirror-example-setup/src/prompt">
}
