// flow-typed signature: a1f200a7980c1539ad80cf14264ef3a1
// flow-typed version: <<STUB>>/prosemirror-state_v1.1.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-state'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prosemirror-state" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prosemirror-state/dist/index" {
  declare module.exports: any
}

declare module "prosemirror-state/rollup.config" {
  declare module.exports: any
}

declare module "prosemirror-state/src/index" {
  declare module.exports: any
}

declare module "prosemirror-state/src/plugin" {
  declare module.exports: any
}

declare module "prosemirror-state/src/selection" {
  declare module.exports: any
}

declare module "prosemirror-state/src/state" {
  declare module.exports: any
}

declare module "prosemirror-state/src/transaction" {
  declare module.exports: any
}

// Filename aliases
declare module "prosemirror-state/dist/index.js" {
  declare module.exports: $Exports<"prosemirror-state/dist/index">
}
declare module "prosemirror-state/rollup.config.js" {
  declare module.exports: $Exports<"prosemirror-state/rollup.config">
}
declare module "prosemirror-state/src/index.js" {
  declare module.exports: $Exports<"prosemirror-state/src/index">
}
declare module "prosemirror-state/src/plugin.js" {
  declare module.exports: $Exports<"prosemirror-state/src/plugin">
}
declare module "prosemirror-state/src/selection.js" {
  declare module.exports: $Exports<"prosemirror-state/src/selection">
}
declare module "prosemirror-state/src/state.js" {
  declare module.exports: $Exports<"prosemirror-state/src/state">
}
declare module "prosemirror-state/src/transaction.js" {
  declare module.exports: $Exports<"prosemirror-state/src/transaction">
}
