// flow-typed signature: 0b5c712f9dcae46cd23c9144c684d43c
// flow-typed version: <<STUB>>/prosemirror-inputrules_v1.0.1/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-inputrules'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prosemirror-inputrules" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prosemirror-inputrules/dist/index" {
  declare module.exports: any
}

declare module "prosemirror-inputrules/rollup.config" {
  declare module.exports: any
}

declare module "prosemirror-inputrules/src/index" {
  declare module.exports: any
}

declare module "prosemirror-inputrules/src/inputrules" {
  declare module.exports: any
}

declare module "prosemirror-inputrules/src/rulebuilders" {
  declare module.exports: any
}

declare module "prosemirror-inputrules/src/rules" {
  declare module.exports: any
}

// Filename aliases
declare module "prosemirror-inputrules/dist/index.js" {
  declare module.exports: $Exports<"prosemirror-inputrules/dist/index">
}
declare module "prosemirror-inputrules/rollup.config.js" {
  declare module.exports: $Exports<"prosemirror-inputrules/rollup.config">
}
declare module "prosemirror-inputrules/src/index.js" {
  declare module.exports: $Exports<"prosemirror-inputrules/src/index">
}
declare module "prosemirror-inputrules/src/inputrules.js" {
  declare module.exports: $Exports<"prosemirror-inputrules/src/inputrules">
}
declare module "prosemirror-inputrules/src/rulebuilders.js" {
  declare module.exports: $Exports<"prosemirror-inputrules/src/rulebuilders">
}
declare module "prosemirror-inputrules/src/rules.js" {
  declare module.exports: $Exports<"prosemirror-inputrules/src/rules">
}
