// flow-typed signature: 59830dfc01b561a2dc7d4be7c015a853
// flow-typed version: <<STUB>>/prosemirror-commands_v1.0.5/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-commands'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prosemirror-commands" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prosemirror-commands/dist/commands" {
  declare module.exports: any
}

declare module "prosemirror-commands/rollup.config" {
  declare module.exports: any
}

declare module "prosemirror-commands/src/commands" {
  declare module.exports: any
}

// Filename aliases
declare module "prosemirror-commands/dist/commands.js" {
  declare module.exports: $Exports<"prosemirror-commands/dist/commands">
}
declare module "prosemirror-commands/rollup.config.js" {
  declare module.exports: $Exports<"prosemirror-commands/rollup.config">
}
declare module "prosemirror-commands/src/commands.js" {
  declare module.exports: $Exports<"prosemirror-commands/src/commands">
}
