// flow-typed signature: f65e4835c576b87430eeaf36099f9c78
// flow-typed version: <<STUB>>/prosemirror-keymap_v1.0.0/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-keymap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prosemirror-keymap" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prosemirror-keymap/dist/keymap" {
  declare module.exports: any
}

declare module "prosemirror-keymap/rollup.config" {
  declare module.exports: any
}

declare module "prosemirror-keymap/src/keymap" {
  declare module.exports: any
}

// Filename aliases
declare module "prosemirror-keymap/dist/keymap.js" {
  declare module.exports: $Exports<"prosemirror-keymap/dist/keymap">
}
declare module "prosemirror-keymap/rollup.config.js" {
  declare module.exports: $Exports<"prosemirror-keymap/rollup.config">
}
declare module "prosemirror-keymap/src/keymap.js" {
  declare module.exports: $Exports<"prosemirror-keymap/src/keymap">
}
