// flow-typed signature: 9c87740e784c174f7792efeaa922c85d
// flow-typed version: <<STUB>>/prosemirror-menu_v1.0.3/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-menu'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prosemirror-menu" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prosemirror-menu/dist/index" {
  declare module.exports: any
}

declare module "prosemirror-menu/rollup.config" {
  declare module.exports: any
}

declare module "prosemirror-menu/src/icons" {
  declare module.exports: any
}

declare module "prosemirror-menu/src/index" {
  declare module.exports: any
}

declare module "prosemirror-menu/src/menu" {
  declare module.exports: any
}

declare module "prosemirror-menu/src/menubar" {
  declare module.exports: any
}

// Filename aliases
declare module "prosemirror-menu/dist/index.js" {
  declare module.exports: $Exports<"prosemirror-menu/dist/index">
}
declare module "prosemirror-menu/rollup.config.js" {
  declare module.exports: $Exports<"prosemirror-menu/rollup.config">
}
declare module "prosemirror-menu/src/icons.js" {
  declare module.exports: $Exports<"prosemirror-menu/src/icons">
}
declare module "prosemirror-menu/src/index.js" {
  declare module.exports: $Exports<"prosemirror-menu/src/index">
}
declare module "prosemirror-menu/src/menu.js" {
  declare module.exports: $Exports<"prosemirror-menu/src/menu">
}
declare module "prosemirror-menu/src/menubar.js" {
  declare module.exports: $Exports<"prosemirror-menu/src/menubar">
}
