// flow-typed signature: d22a568f1a442303d2c2dc40bd3c512a
// flow-typed version: <<STUB>>/prosemirror-markdown_v1.0.3/flow_v0.64.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prosemirror-markdown" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prosemirror-markdown/dist/index" {
  declare module.exports: any
}

declare module "prosemirror-markdown/rollup.config" {
  declare module.exports: any
}

declare module "prosemirror-markdown/src/from_markdown" {
  declare module.exports: any
}

declare module "prosemirror-markdown/src/index" {
  declare module.exports: any
}

declare module "prosemirror-markdown/src/schema" {
  declare module.exports: any
}

declare module "prosemirror-markdown/src/to_markdown" {
  declare module.exports: any
}

// Filename aliases
declare module "prosemirror-markdown/dist/index.js" {
  declare module.exports: $Exports<"prosemirror-markdown/dist/index">
}
declare module "prosemirror-markdown/rollup.config.js" {
  declare module.exports: $Exports<"prosemirror-markdown/rollup.config">
}
declare module "prosemirror-markdown/src/from_markdown.js" {
  declare module.exports: $Exports<"prosemirror-markdown/src/from_markdown">
}
declare module "prosemirror-markdown/src/index.js" {
  declare module.exports: $Exports<"prosemirror-markdown/src/index">
}
declare module "prosemirror-markdown/src/schema.js" {
  declare module.exports: $Exports<"prosemirror-markdown/src/schema">
}
declare module "prosemirror-markdown/src/to_markdown.js" {
  declare module.exports: $Exports<"prosemirror-markdown/src/to_markdown">
}
