// flow-typed signature: f87812a2c1b56709171f2bb3f3ed12f4
// flow-typed version: <<STUB>>/prosemirror-schema-list_v1.0.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'prosemirror-schema-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "prosemirror-schema-list" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "prosemirror-schema-list/dist/schema-list" {
  declare module.exports: any
}

declare module "prosemirror-schema-list/rollup.config" {
  declare module.exports: any
}

declare module "prosemirror-schema-list/src/schema-list" {
  declare module.exports: any
}

// Filename aliases
declare module "prosemirror-schema-list/dist/schema-list.js" {
  declare module.exports: $Exports<"prosemirror-schema-list/dist/schema-list">
}
declare module "prosemirror-schema-list/rollup.config.js" {
  declare module.exports: $Exports<"prosemirror-schema-list/rollup.config">
}
declare module "prosemirror-schema-list/src/schema-list.js" {
  declare module.exports: $Exports<"prosemirror-schema-list/src/schema-list">
}
