// flow-typed signature: bb041fce7cc75028266cb4cbcbab6d06
// flow-typed version: <<STUB>>/rollup-plugin-serve_v0.4.2/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-serve'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rollup-plugin-serve" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "rollup-plugin-serve/dist/index.cjs" {
  declare module.exports: any
}

declare module "rollup-plugin-serve/dist/index.es" {
  declare module.exports: any
}

// Filename aliases
declare module "rollup-plugin-serve/dist/index.cjs.js" {
  declare module.exports: $Exports<"rollup-plugin-serve/dist/index.cjs">
}
declare module "rollup-plugin-serve/dist/index.es.js" {
  declare module.exports: $Exports<"rollup-plugin-serve/dist/index.es">
}
