// flow-typed signature: 7b13d74deff781d5d7957ecff75e04bc
// flow-typed version: <<STUB>>/rollup-plugin-legacy_v1.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-legacy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "rollup-plugin-legacy" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "rollup-plugin-legacy/dist/rollup-plugin-legacy.cjs" {
  declare module.exports: any
}

declare module "rollup-plugin-legacy/dist/rollup-plugin-legacy.es" {
  declare module.exports: any
}

// Filename aliases
declare module "rollup-plugin-legacy/dist/rollup-plugin-legacy.cjs.js" {
  declare module.exports: $Exports<
    "rollup-plugin-legacy/dist/rollup-plugin-legacy.cjs"
  >
}
declare module "rollup-plugin-legacy/dist/rollup-plugin-legacy.es.js" {
  declare module.exports: $Exports<
    "rollup-plugin-legacy/dist/rollup-plugin-legacy.es"
  >
}
