// flow-typed signature: 375ddc9e62568954119777d358aee20c
// flow-typed version: <<STUB>>/@beaker/webdb_v4.1.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@beaker/webdb'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module "@beaker/webdb" {
  declare module.exports: any
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module "@beaker/webdb/lib/errors" {
  declare module.exports: any
}

declare module "@beaker/webdb/lib/indexed-level" {
  declare module.exports: any
}

declare module "@beaker/webdb/lib/indexer" {
  declare module.exports: any
}

declare module "@beaker/webdb/lib/query" {
  declare module.exports: any
}

declare module "@beaker/webdb/lib/table-def" {
  declare module.exports: any
}

declare module "@beaker/webdb/lib/table" {
  declare module.exports: any
}

declare module "@beaker/webdb/lib/util-level" {
  declare module.exports: any
}

declare module "@beaker/webdb/lib/util" {
  declare module.exports: any
}

declare module "@beaker/webdb/lib/where-clause" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/helper-tables" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/indexed-level" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/indexer-no-watch" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/indexer-single-file" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/indexer" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/lib/util" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/multi-def-index" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/multi-entry-index" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/preprocessor-serializer" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/query-mutators" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/query" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/schemas" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/table-mutators" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/table" {
  declare module.exports: any
}

declare module "@beaker/webdb/test/where-clause" {
  declare module.exports: any
}

// Filename aliases
declare module "@beaker/webdb/index" {
  declare module.exports: $Exports<"@beaker/webdb">
}
declare module "@beaker/webdb/index.js" {
  declare module.exports: $Exports<"@beaker/webdb">
}
declare module "@beaker/webdb/lib/errors.js" {
  declare module.exports: $Exports<"@beaker/webdb/lib/errors">
}
declare module "@beaker/webdb/lib/indexed-level.js" {
  declare module.exports: $Exports<"@beaker/webdb/lib/indexed-level">
}
declare module "@beaker/webdb/lib/indexer.js" {
  declare module.exports: $Exports<"@beaker/webdb/lib/indexer">
}
declare module "@beaker/webdb/lib/query.js" {
  declare module.exports: $Exports<"@beaker/webdb/lib/query">
}
declare module "@beaker/webdb/lib/table-def.js" {
  declare module.exports: $Exports<"@beaker/webdb/lib/table-def">
}
declare module "@beaker/webdb/lib/table.js" {
  declare module.exports: $Exports<"@beaker/webdb/lib/table">
}
declare module "@beaker/webdb/lib/util-level.js" {
  declare module.exports: $Exports<"@beaker/webdb/lib/util-level">
}
declare module "@beaker/webdb/lib/util.js" {
  declare module.exports: $Exports<"@beaker/webdb/lib/util">
}
declare module "@beaker/webdb/lib/where-clause.js" {
  declare module.exports: $Exports<"@beaker/webdb/lib/where-clause">
}
declare module "@beaker/webdb/test/helper-tables.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/helper-tables">
}
declare module "@beaker/webdb/test/indexed-level.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/indexed-level">
}
declare module "@beaker/webdb/test/indexer-no-watch.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/indexer-no-watch">
}
declare module "@beaker/webdb/test/indexer-single-file.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/indexer-single-file">
}
declare module "@beaker/webdb/test/indexer.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/indexer">
}
declare module "@beaker/webdb/test/lib/util.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/lib/util">
}
declare module "@beaker/webdb/test/multi-def-index.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/multi-def-index">
}
declare module "@beaker/webdb/test/multi-entry-index.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/multi-entry-index">
}
declare module "@beaker/webdb/test/preprocessor-serializer.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/preprocessor-serializer">
}
declare module "@beaker/webdb/test/query-mutators.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/query-mutators">
}
declare module "@beaker/webdb/test/query.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/query">
}
declare module "@beaker/webdb/test/schemas.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/schemas">
}
declare module "@beaker/webdb/test/table-mutators.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/table-mutators">
}
declare module "@beaker/webdb/test/table.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/table">
}
declare module "@beaker/webdb/test/where-clause.js" {
  declare module.exports: $Exports<"@beaker/webdb/test/where-clause">
}
